<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // helper to fetch the category ID by slug
        $cat = fn(string $slug) => DB::table('categories')
                                     ->where('slug', $slug)
                                     ->value('id');

        DB::table('projects')->insert([
            // Existing Projects
            [
                'project_type' => 'Web App',
                'project_name' => 'iTechPlus Dashboard',
                'description'  => 'A portal for businesses to browse and request quotes on tech projects.',
                'cover_image'  => 'itechplus.png',
                'date'         => '2025-05-01',
                'category_id'  => $cat('digital-transformation'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Research',
                'project_name' => 'SPUP Alumni Tracer Study',
                'description'  => 'Collects and analyzes alumni career data for SPUP.',
                'cover_image'  => 'alumni-tracer.png',
                'date'         => '2024-10-15',
                'category_id'  => $cat('digital-transformation'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Mobile App',
                'project_name' => 'Food Delivery Robot UI',
                'description'  => 'Flutter frontend for controlling an AI-powered delivery robot.',
                'cover_image'  => 'robot-ui.jpg',
                'date'         => '2024-08-11',
                'category_id'  => $cat('transportation'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],

            // Livelihood
            [
                'project_type' => 'Product',
                'project_name' => 'Mucovado Sugar',
                'description'  => 'Muscovado sugar is pure, whole, unrefined, and non-centrifugal cane sugar that retains all of the natural minerals of sugarcane.',
                'cover_image'  => 'mucovado-sugar.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('livelihood'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Integrated Wrought Iron Forming Equipment (I-WIFE)',
                'description'  => 'The Wrought Iron Forming Equipment is a portable, robust, quick set-up forming equipment that can bend, roll, curl and twist metal flat strips, square bars and round bars. It helps complete decorative furniture, agricultural and industrial metal projects faster and easier. The mobile tool box serves as a base and accessories hold for on-site fabrication works.',
                'cover_image'  => '(I-WIFE).jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('livelihood'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => "Electric Potter's Wheel",
                'description'  => 'The Electric Potter\'s Wheel is a motor driven, adjustable speed, compact machine for shaping ceramic clay into round ceramic ware. It can also be used for trimming excess material from dried ware and for applying decoration or rings of colors. The 14-inch wheel head plate speed (range: 0 to 250 rpm) can be controlled using a presser pedal, in a clockwise or counterclockwise direction. Motor: 1/2 Hp, brushless, 220V, 60Hz, Single-Phase. The main body is powder coated for protection from rust.',
                'cover_image'  => 'electric-potters-wheel.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('livelihood'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Tikog Presser',
                'description'  => 'The Tikog Presser is an easy to set-up and operator friendly flattening machine for faster flattening of "tikog" and other indigenous leaves for handicraft products. The use of stainless steel hollow rollers and gears makes it lighter and more compact. Overall dimension: 370mm x 490mm x 300mm (excluding 120mm Stand). Net weight is 29.6 kg (+ 3.8kg for base stand (optional)).',
                'cover_image'  => 'tikog-presser.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('livelihood'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Pandanus Leaves Slitter - Presser',
                'description'  => 'A hand operated machine used to flatten and cut bariw leaves (also called pandan leaves) into several strips that can be varied into 5, 10 or 15mm width for handicraft production. The resulting bariw leaves strips have improved texture and generally uniform thickness and width size. It replaces the tedious manual process currently practiced by local handicraft weavers. Overall Dimension: 1042mm x 610mm x 1048mm.',
                'cover_image'  => 'pandanus-leaves-slitter-presser.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('livelihood'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Abaca Fiber Extractor',
                'description'  => 'An abaca fiber extractor is an apparatus to extract abaca fiber from a strip of tuxy. The abaca fiber extractor comprises a body, a blade holder, a blade, a shaft housing, a pusher shaft, a spring, a lever, and a storage.',
                'cover_image'  => 'abaca-fiber-extractor.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('livelihood'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],

            // Food
            [
                'project_type' => 'Process',
                'project_name' => 'Ready-to-Eat Boneless Milkfish Simmered in Vinegar',
                'description'  => 'A process of producing ready-to-eat boneless milkfish simmered in vinegar that speeds preparation in convenient packaging. Steps include: preparing ingredients, cutting fish, mixing with spices and vinegar, simmering, cooling, filling containers, adding broth and finger chilis, and cooking in a batch-type, vertical non-agitating water retort for 60 minutes at 116°C.',
                'cover_image'  => 'boneless-milkfish.jpg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('food'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Rice Harvester Attachment',
                'description'  => 'An efficient rice harvesting implement that can be readily mounted to and dismounted from the hand tractor unit, increasing utilization and reducing labor cost. Estimated capacity: 0.5 ha/day for an eight-hour operation.',
                'cover_image'  => 'rice-harvester-attachment.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('food'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Rice Transplanter Attachment',
                'description'  => 'A rice transplanter implement that can be readily mounted to and dismounted from a common hand tractor. Designed to increase utilization and reduce farm-level mechanization costs for planters.',
                'cover_image'  => 'rice-transplanter-attachment.jpg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('food'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Product',
                'project_name' => 'Nutrio® Biofertilizer for Eggplant and Sugarcane',
                'description'  => 'Nutrio® is a biofertilizer using endophytic bacterial inoculants to promote nitrogen fixation and plant growth for eggplant and sugarcane. A foliar spray in powder form, it can be directly applied to crops.',
                'cover_image'  => 'nutrio-biofertilizer.jpg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('food'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Compact Ultra Impeller Rice Mill',
                'description'  => 'An impeller-type rice mill machine with a milling capacity of 230kg/hour. Produces both white and brown rice with recovery rates higher than rubber roll type by 5%. Suitable for village-level operation.',
                'cover_image'  => 'compact-ultra-impeller-rice-mill.png',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('food'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Product',
                'project_name' => 'BioGroe®',
                'description'  => 'BioGroe® is a solid-based microbial inoculant containing plant-growth-promoting bacteria (PGPB) that induces root growth by producing hormones and providing soluble nutrients. When used with chemical fertilizer, it significantly increases growth and productivity of crops like corn and rice.',
                'cover_image'  => 'biogrow.png',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('food'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],

            // Health
            [
                'project_type' => 'Prototype',
                'project_name' => 'AGAPAY',
                'description'  => 'AGAPAY is a robotic exoskeleton prototype with biofeedback for rehabilitation of post-stroke and injured patients, assisting motor movements in shoulders, arms, and hands. 3D-printed biomedical devices record neuromuscular activity via surface electromyography.',
                'cover_image'  => 'AGAPAY.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('health'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Product',
                'project_name' => 'Akapulco Lotion',
                'description'  => 'An affordable herbal medicine for treating fungal skin infections like ringworm, scabies, and eczema. Clinically proven as effective as synthetic antifungal agents.',
                'cover_image'  => 'akapulco-lotion.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('health'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Axis Knee System',
                'description'  => 'A primary posterior-stabilized total knee replacement with symmetric tibial component. Patented instrumentation determines the mechanical axis without x-rays or navigation, and allows sizing and gap assessment prior to bone cutting.',
                'cover_image'  => 'axis-knee-system.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('health'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Axis Revision Knee System',
                'description'  => 'A revision total knee replacement system with modular components to accommodate a wide range of bony defects.',
                'cover_image'  => 'axis-revision-knee-system.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('health'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Product',
                'project_name' => 'Biotek M Dengue Detection Kit',
                'description'  => 'A rapid confirmatory test kit for dengue infection diagnosis within the first 0-5 days of illness. Delivers results in under an hour and designed for minimal lab facilities.',
                'cover_image'  => 'biotek-m-dengue-detection-kit.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('health'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Web App',
                'project_name' => 'CHITS',
                'description'  => 'CHITS (Community Health Information Tracking System) is an electronic medical record system that reduces patient wait times and automates report transmission to the Philippine Health Insurance Corporation.',
                'cover_image'  => 'CHITS.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('health'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],

            // Water & Environment
            [
                'project_type' => 'Equipment & Process',
                'project_name' => 'Equipment System and Process for Treating Wastewater from Wet-Type Finishing Spray Booths',
                'description'  => 'A system and process for treating wastewater from wet-type finishing spray booths, removing contaminants via a water curtain filter that captures up to 99% of excess spray.',
                'cover_image'  => 'equipment-system-and-process-for-treating-wastewater-from-wet-type-finishing-spray-booths.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('water-environment'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Finishing Spray Booth',
                'description'  => 'An enclosure for controlling paint spray during finishing operations. Available in dry-filter and wet-filter types, enhancing air quality and worker safety.',
                'cover_image'  => 'finishing-spray-booth.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('water-environment'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Jigger and Jolly Machine',
                'description'  => 'A motor driven, adjustable speed machine for shaping ceramic clay into flat and hollow wares. Speed controlled by presser pedal; body is powder coated against rust.',
                'cover_image'  => 'jigger-and-jolly-machine.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('water-environment'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Product',
                'project_name' => 'Non-cyanide Gold Electroplating Solution',
                'description'  => 'A cyanide-free gold plating solution that reduces toxicity and simplifies waste treatment, improving safety and environmental impact.',
                'cover_image'  => 'non-cyanide-gold-electroplating-solution.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('water-environment'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Device',
                'project_name' => 'Electrochemical Sensor for Heavy Metal Detection in Water',
                'description'  => 'A portable electrode modified with bismuth nanoparticles and Nafion® for on-site routine analysis of heavy metals in water.',
                'cover_image'  => 'electrochemical-sensor-for-heavy-metal-detection-in-water.jpg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('water-environment'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Process',
                'project_name' => 'Method for Detecting Haloacetic Acids in Bromide- and Chloride-Rich Water Systems',
                'description'  => 'A method to detect haloacetic acids formed during disinfection, providing data to develop measures that prevent formation of harmful by-products in drinking water.',
                'cover_image'  => 'method-for-detecting-haloacetic-acids-in-bromide-and-chloride-rich-water-systems.jpg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('water-environment'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],

            // Energy
            [
                'project_type' => 'Equipment',
                'project_name' => 'Therapeutic Handloom Weaving Machine',
                'description'  => 'A four-harness handloom weaving machine designed for paraplegics, equipped with sliding beater and hand-held lever, mountable on a standard wheelchair.',
                'cover_image'  => 'therapeutic-handloom-weaving-machine.jpg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('energy'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Portable Vulcanizing Device',
                'description'  => 'A vulcanizing apparatus powered by a 12V car or motorcycle battery, featuring a tripod stand and removable heater assembly for on-the-go tire repair.',
                'cover_image'  => 'portable-vulcanizing-device.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('energy'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Equipment',
                'project_name' => 'Solar Powered Weather Instrument Simulator',
                'description'  => 'A solar powered weather instrument simulator intended for instructional purposes in meteorology, featuring a wind vane, anemometer, solar panel, and monitoring unit.',
                'cover_image'  => 'solar-powered-weather-instrument-simulator.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('energy'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Energy Storage',
                'project_name' => 'JOLT',
                'description'  => 'A stackable multi-functional battery energy storage system designed for modular scalability and on-demand power release.',
                'cover_image'  => 'jolt.jpg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('energy'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Energy Storage',
                'project_name' => 'Fabric Supercapacitor',
                'description'  => 'A flexible supercapacitor using fabric-based electrodes for wearable energy storage, bridging the gap between solar/wind variability and demand.',
                'cover_image'  => 'fabric-supercapacitor.jpg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('energy'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],

            // Transportation
            [
                'project_type' => 'Process',
                'project_name' => 'Wood Processing - Rubberwood, Gmelina, Mahogany, and Other Plantation Species',
                'description'  => 'Techniques in wood and cocowood sawmilling, drying/seasoning, treatment/preservation, and finishing for various plantation species.',
                'cover_image'  => 'wood-processing-rubberwood-gmelina-mahogany-and-other-plantation-species-coco-wood.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('transportation'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Vehicle',
                'project_name' => 'Hybrid Electric Road Train (HERT)',
                'description'  => 'A multiple-coach urban mass transit vehicle with diesel-electric hybrid system and lithium-ion batteries, designed to reduce diesel consumption and emissions.',
                'cover_image'  => 'hybrid-electric-road-train-hert.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('transportation'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Vehicle',
                'project_name' => 'Hybrid Electric Train (HET)',
                'description'  => 'A diesel-electric hybrid train with regenerative braking, air conditioning, and anti-climbing safety features, developed and tested for PNR commuter service.',
                'cover_image'  => 'hybrid-electric-train-het.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('transportation'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],

            // Digital Transformation
            [
                'project_type' => 'Device',
                'project_name' => 'Portable Biogas Digester',
                'description'  => 'An air-tight, oxygen-free vessel for microbial digestion of organic waste to produce biogas for cooking and sludge as soil conditioner.',
                'cover_image'  => 'portable-biogas-digester.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('digital-transformation'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
            [
                'project_type' => 'Mobile App',
                'project_name' => 'Kooha: A Social Sensing Network Application',
                'description'  => 'Kooha is a mobile photo-sharing application for participatory photo and sensor data collection, capturing location, temperature, sound, and more, facilitating insights for researchers and citizen scientists.',
                'cover_image'  => 'kooha.jpeg',
                'date'         => $now->toDateString(),
                'category_id'  => $cat('digital-transformation'),
                'created_at'   => $now,
                'updated_at'   => $now,
            ],
        ]);
    }
}
